### ISSUE TITLE
前端界面展示

### ISSUE THREAD

**Issue by provenclei** [TylunasLi/ChatGLM-web-stream-demo#2]
请问下前端的static文件，是如何配置进行展示的？

**Comment by TylunasLi** [comment]
作为线上服务，分为两种情况：
* 如果您使用Flask，那么默认配置下，工程中"static/"目录中的下所有文件都当作静态资源文件访问；
* 如果您使用fastapi，那么static目录可以通过http服务器（如nginx、apache）挂载，

如果这并非线上服务，直接浏览器打开html即可。

**Comment by TylunasLi** [comment]
9c42b6c8 已更新FastAPI下静态资源加载，目前可以浏览器访问了。
